language: generic 

sudo: required

services:
  - docker

before_install:
  - docker build -t sm/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true sm/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-udemy"
  environment: "Dockerudemy-env"
  bucket_name: "elasticbeanstalk-us-east-1-277269668171"
  bucket_path: "docker-udemy"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"